### ISSUE TITLE
Cannot install any R packages

### ISSUE THREAD

**Issue by dquang** [its-pointless/gcc_termux#11]
Hi, 

I was able to install R and R runs well on my Samsung G. Tab S2, Android 7. However, I cannot install any R packages, they all produced 'non-zero exit status'. Do you have any ideas about that?

Thanks,
Quang

**Comment by clancia** [comment]
Hi, first of all I should like to warmly thank you for making the repo available.
Your work is extremely valuable for me.

I am having similar issues with installing packages.
Here are some details:

1. Some packages do install.
2. Those requiring compilation fail because of `./configure: No such file or directory`, which can be fixed by installing `proot` and the command `termux-chroot`
3. Now I am getting this error:
`/data/data/com.termux/files/usr/bin/ld: cannot find -lgfortran
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)`

Looks like it's compiling packages against clang and not gcc

**Comment by clancia** [comment]
After installing `gcc-7`, create `˜/.R/Makevars` and add these lines
`CC = gcc-7
F77 = gfortran-7
FC = gfortran-7
FLIBS = -L/data/data/com.termux/files/usr/lib`

**Comment by its-pointless** [comment]
The command setupgcc-7 and setupclang are there for this kind of thing.
also to avoid issues with /bin/sh  not being found there is libandroid-fixshebang.c here but i havent provoded instructions yet. I will bet around to that shortly. I should provide more documentation for this enviroment.
