### ISSUE TITLE
no default toolchain configured for rustc or cargo

### ISSUE THREAD

**Issue by wzhd** [its-pointless/gcc_termux#15]
When I run `rustc` or `cargo`, I can only get an error and nothing else:

> error: no default toolchain configured

I've installed `libllvm-4so`, is there anything else that should be done?

`clang` is now 5.0.0 and rustc depends on it, would it be a problem?

Thanks!

**Comment by its-pointless** [comment]
unfortunately this is an issue for i686 and x86_64.  
Could` not create LLVM TargetMachine for triple: i686-linux-android: Unable to find target for this triple (no targets are registered) 
that error is from libllvm. and more annoyingly from version 4.0.1. i have no idea how to fix this since i do not do llvm stuff often.

**Comment by its-pointless** [comment]
okay iv gotten i686 rustc working

**Comment by its-pointless** [comment]
Rustc working on all archs now afaik
